import './test-env.ts';
import assert from 'node:assert/strict';
import Fastify from 'fastify';
import { parseMenuSchoolIds, getSettings, updateSettings } from '../src/core/settings.ts';
import { fetchSelectedMenus, selectedMenuData } from '../src/providers/menu.ts';
import { parseMenuSchools, fetchMenuSchools } from '../src/core/menu-schools.ts';
import { registerApiRoutes } from '../src/routes/api.ts';
const now=new Date('2026-12-29T12:00:00Z');
const page=(id:string)=>({result:{pageContext:{menu:{RestaurantId:id,RestaurantName:'Koulu '+id,Start:'2026-12-28',Days:[{Date:'maanantai 28.12.',Meals:[{MealType:'Lounas',Name:'Keitto '+id}]}]}}}});
assert.deepEqual(parseMenuSchoolIds(['a','a','b']),['a','b']);assert.deepEqual(parseMenuSchoolIds([]),[]);
for(const bad of [null,'a',['../foo'],['https://example.com'],Array(9).fill('a'),['a/b']])assert.throws(()=>parseMenuSchoolIds(bad));
updateSettings({menuSchoolIds:['a','b']});assert.deepEqual(getSettings().menuSchoolIds,['a','b']);
assert.throws(()=>updateSettings({menuSchoolIds:['../bad']}));assert.deepEqual(getSettings().menuSchoolIds,['a','b']);
let ids=['a'];let release!:()=>void;let started!:()=>void;
const start=new Promise<void>(r=>started=r), gate=new Promise<void>(r=>release=r);const calls:string[]=[];
const result=fetchSelectedMenus((async url=>{const id=String(url).split('/menu/')[1]!.split('/')[0]!;calls.push(id);if(id==='a'){started();await gate;}return Response.json(page(id));}) as typeof fetch,()=>ids,null,now);
await start;ids=['b'];release();
assert.deepEqual((await result).schools.map(s=>s.locationId),['b']);assert.ok(calls.includes('b'));
const old={locationId:'a',locationName:'Vanha koulu',sourceUrl:'https://kouluruoka.fi/menu/a/',days:[]};
assert.equal(selectedMenuData(old,['a'],'2026-12-28T10:00:00Z').schools[0]?.locationName,'Vanha koulu');
assert.equal(selectedMenuData(old,['b']).schools[0]?.status,'loading');
assert.deepEqual(selectedMenuData(old,[]).schools,[]);
const multi=await fetchSelectedMenus((async url=>String(url).includes('/a/')?Response.json(page('a')):new Response(null,{status:503})) as typeof fetch,()=>['a','b'],{schools:[{...old,locationId:'b',locationName:'Koulu b',status:'ok',error:null,fetchedAt:'2026-12-28T10:00:00Z'}]},now);
assert.equal(multi.schools[0]?.status,'ok');assert.equal(multi.schools[1]?.status,'stale');assert.match(multi.schools[1]!.error!,/503/);
const empty=await fetchSelectedMenus((async()=>{throw Error('must not fetch');}) as typeof fetch,()=>[],null,now);assert.deepEqual(empty.schools,[]);
const catalog={data:{allAzureJson:{nodes:[{WeekMenu:[{RestaurantId:'a',RestaurantName:'Koulu A',CityName:'Kunta'}]},{WeekMenu:[{RestaurantId:'a',RestaurantName:'Koulu A',CityName:'Kunta'},{RestaurantId:'../bad',RestaurantName:'Bad',CityName:'Bad'}]}]}}};
assert.deepEqual(parseMenuSchools(catalog),[{id:'a',name:'Koulu A',city:'Kunta'}]);
assert.equal((await fetchMenuSchools((async url=>Response.json(String(url).includes('/index/')?{staticQueryHashes:['12','34']}:String(url).includes('/12.')?catalog:{})) as typeof fetch)).length,1);
await assert.rejects(()=>fetchMenuSchools((async()=>Response.json({staticQueryHashes:['https://evil']})) as typeof fetch));
const app=Fastify();await registerApiRoutes(app);
const denied=await app.inject({method:'PUT',url:'/api/settings',remoteAddress:'203.0.113.25',payload:{menuSchoolIds:['c']}});assert.equal(denied.statusCode,403);assert.deepEqual(getSettings().menuSchoolIds,['a','b']);
const saved=await app.inject({method:'PUT',url:'/api/settings',remoteAddress:'127.0.0.1',payload:{menuSchoolIds:[]}});assert.equal(saved.statusCode,200);assert.deepEqual(saved.json().menuSchoolIds,[]);
await app.close();
console.log('Menu selection: validation, settings/auth, multiple schools, partial failures, legacy cache, in-flight change, empty selection and dynamic catalogue passed');
